# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 4, 16, 34, 67000)),
        ),
    ]
